### ISSUE TITLE
Algorithm sometimes schedules too few classes a quarter [v0.5.2]

### ISSUE THREAD

**Issue by jocelync888** [park-junha/PlanForGrad#106]
<img width="1221" alt="Screen Shot 2020-01-30 at 5 24 16 PM" src="https://user-images.githubusercontent.com/60240262/73504797-6c01f380-4385-11ea-8dbf-30316cd72fe6.png">

My CS friend tried testing out the website for their schedule. Why is there only one class in Winter 2021 and another in spring. Shouldn't they both be combined into Winter???

**Comment by park-junha** [comment]
This particular scenario happens because CSCI 181 is only offered Spring quarter every other year.

This behavior can also be seen [here](http://gradplanner.herokuapp.com/schedule?inputtedMajor=Computer-Science.-Security-Emphasis&questionMajorClassesTaken=CSCI-10-and-L&questionMajorClassesTaken=MATH-11&questionMajorClassesTaken=CSCI-60-and-L&questionMajorClassesTaken=MATH-12&questionMajorClassesTaken=MATH-13&questionCoresTaken=CTW-1&questionCoresTaken=Culture-and-Ideas-1&electiveUnits=12):
![Screen Shot 2020-01-31 at 8 54 34 AM](https://user-images.githubusercontent.com/48537888/73558115-63ea9800-4407-11ea-8771-23ecafe0e32a.png)
Reproducible on [master](https://github.com/park-junha/PlanForGrad/tree/0d7a0c7df8adf932fbe761cdb48fc81982d96be8) at `v0.5.2` by inputting:
- **Major:** Computer Science, Security Emphasis
- Start from Spring 2019-2020
- **Major classes taken:** CSCI 10 & 60, MATH 11-13, CTW 1, C&I 1, 12 elective units

**Potential fix:** Have the algorithm fill in non-full quarters with more electives, even if it isn't required for graduation, and label them as "Highly recommended".

**Comment by park-junha** [comment]
Fix immediately after #109

**Comment by park-junha** [comment]
#95 will be handled by this also
