### ISSUE TITLE
Web app should display current version + display an "under construction" zone

### ISSUE THREAD

**Issue by park-junha** [park-junha/PlanForGrad#76]
Website should display current version somewhere, perhaps on the corner on a footer

**Comment by park-junha** [comment]
Maybe looks like this?
![Screen Shot 2020-01-24 at 8 22 57 AM](https://user-images.githubusercontent.com/48537888/73085002-da751c00-3e82-11ea-9d29-c6b37bd271aa.png)

**Comment by park-junha** [comment]
reassigning to @Hanzhuo-Gong

**Comment by park-junha** [comment]
Make sure footer is fixed (Bootstrap) @Hanzhuo-Gong

**Comment by Hanzhuo-Gong** [comment]
<img width="1440" alt="Screen Shot 2020-01-24 at 3 46 48 PM" src="https://user-images.githubusercontent.com/32682736/73111920-1dee7b00-3ec1-11ea-9833-13c85d38149d.png">

Version is fixed with the under construction. Question is do we need version for every pages? or just home page. Let me know if you guys have any suggestions for the website

**Comment by park-junha** [comment]
@Hanzhuo-Gong any chance we can get it on the bottom right of the footer? i think we should have it on all pages and it shouldn't be too distracting
